_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: f047fa5b-89c8-4f6b-80de-7ea36c91cf55
name: 'D10 on CG Test - 20240109.001'
mail: katherine.jones@koniag-gs.com
slogan: 'Read from Config'
page:
  403: ''
  404: ''
  front: /node/1
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
